--------------------------------------------------------
--  File created - Th? ba-tháng tý-16-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "ANHQUOC4062"."CATEGORIES" 
   (	"IDCATEGORY" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STRCATEGORY" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ANHQUOC4062.CATEGORIES
SET DEFINE OFF;
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('1','Ordinary Drink');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('2','Cocktail');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('3','Milk / Float / Shake');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('4','Other/Unknown');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('5','Cocoa');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('6','Shot');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('7','Coffee / Tea');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('8','Homemade Liqueur');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('9','Punch / Party Drink');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('10','Beer');
Insert into ANHQUOC4062.CATEGORIES (IDCATEGORY,STRCATEGORY) values ('11','Soft Drink / Soda');
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "ANHQUOC4062"."CATEGORIES" MODIFY ("IDCATEGORY" NOT NULL ENABLE);
