--------------------------------------------------------
--  File created - Th? ba-tháng tý-16-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INGREDIENT
--------------------------------------------------------

  CREATE TABLE "ANHQUOC4062"."INGREDIENT" 
   (	"IDINGREDIENT" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STRINGREDIENT1" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ANHQUOC4062.INGREDIENT
SET DEFINE OFF;
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('1','Light rum');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('2','Applejack');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('3','Gin');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('4','Dark rum');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('5','Sweet Vermouth');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('6','Strawberry schnapps');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('7','Scotch');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('8','Apricot brandy');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('9','Triple sec');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('10','Southern Comfort');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('11','Orange bitters');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('12','Brandy');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('13','Lemon vodka');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('14','Blended whiskey');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('15','Dry Vermouth');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('16','Amaretto');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('17','Tea');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('18','Champagne');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('19','Coffee liqueur');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('20','Bourbon');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('21','Tequila');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('22','Vodka');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('23','Añejo rum');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('24','Bitters');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('25','Sugar');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('26','Kahlua');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('27','demerara Sugar');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('28','Dubonnet Rouge');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('29','Lime juice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('30','Irish whiskey');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('31','Apple brandy');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('32','Carbonated water');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('33','Cherry brandy');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('34','Creme de Cacao');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('35','Grenadine');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('36','Port');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('37','Coffee brandy');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('38','Red wine');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('39','Rum');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('40','Grapefruit juice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('41','Ricard');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('42','Sherry');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('43','Cognac');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('44','Sloe gin');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('45','Apple juice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('46','Pineapple juice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('47','Lemon juice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('48','Sugar syrup');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('49','Milk');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('50','Strawberries');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('51','Chocolate syrup');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('52','Yoghurt');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('53','Mango');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('54','Ginger');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('55','Lime');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('56','Cantaloupe');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('57','Berries');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('58','Grapes');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('59','Kiwi');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('60','Tomato juice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('61','Cocoa powder');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('62','Chocolate');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('63','Heavy cream');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('64','Galliano');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('65','Peach Vodka');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('66','Ouzo');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('67','Coffee');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('68','Spiced rum');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('69','Water');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('70','Espresso');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('71','Angelica root');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('72','Orange');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('73','Cranberries');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('74','Johnnie Walker');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('75','Apple cider');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('76','Everclear');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('77','Cranberry juice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('78','Egg yolk');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('79','Egg');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('80','Grape juice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('81','Peach nectar');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('82','Lemon');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('83','Firewater');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('84','Lemonade');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('85','Lager');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('86','Whiskey');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('87','Absolut Citron');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('88','Pisco');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('89','Irish cream');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('90','Ale');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('91','Chocolate liqueur');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('92','Midori melon liqueur');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('93','Sambuca');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('94','Cider');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('95','Sprite');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('96','7-Up');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('97','Blackberry brandy');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('98','Peppermint schnapps');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('99','Creme de Cassis');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('100','Jack Daniels');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('101','Bailey''s irish cream');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('102','151 proof rum');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('103','Absolut Vodka');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('104','Goldschlager');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('105','Crown Royal');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('106','Cointreau');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('107','Vermouth');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('108','Advocaat');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('109','Absolut Kurant');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('110','Beer');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('111','Kool-Aid');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('112','Cherry Heering');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('113','White Creme de Menthe');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('114','Malibu rum');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('115','Vanilla vodka');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('116','Jägermeister');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('117','Kiwi liqueur');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('118','Grand Marnier');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('119','Cachaca');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('120','Peachtree schnapps');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('121','Wild Turkey');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('122','Cranberry vodka');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('123','Corona');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('124','Orange juice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('125','Yukon Jack');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('126','Chocolate ice-cream');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('127','Coconut rum');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('128','Banana liqueur');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('129','Black Sambuca');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('130','Hot Damn');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('131','Mint');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('132','Campari');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('133','Ice');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('134','Sour mix');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('135','Absinthe');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('136','Whisky');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('137','Guinness stout');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('138','Vanilla ice-cream');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('139','Chambord raspberry liqueur');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('140','Jim Beam');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('141','Godiva liqueur');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('142','Fruit punch');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('143','Baileys irish cream');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('144','Zima');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('145','Blue Curacao');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('146','Coca-Cola');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('147','Maui');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('148','Frangelico');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('149','Bacardi Limon');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('150','Raspberry vodka');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('151','Green Creme de Menthe');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('152','Lemon peel');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('153','Prosecco');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('154','White Rum');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('155','Mezcal');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('156','Green Chartreuse');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('157','Grape Soda');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('158','Hot Chocolate');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('159','Blended Scotch');
Insert into ANHQUOC4062.INGREDIENT (IDINGREDIENT,STRINGREDIENT1) values ('160','Rye whiskey');
--------------------------------------------------------
--  DDL for Index INGREDIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANHQUOC4062"."INGREDIENT_PK" ON "ANHQUOC4062"."INGREDIENT" ("IDINGREDIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INGREDIENT
--------------------------------------------------------

  ALTER TABLE "ANHQUOC4062"."INGREDIENT" MODIFY ("IDINGREDIENT" NOT NULL ENABLE);
  ALTER TABLE "ANHQUOC4062"."INGREDIENT" ADD CONSTRAINT "INGREDIENT_PK" PRIMARY KEY ("IDINGREDIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
